### ISSUE TITLE
Preparação do ambiente

### ISSUE THREAD

**Issue by aislansf** [atlantico-academy/storm-tellers#1]
- [x] @bcnishi 
- [x] @gabryelsguedes 
- [x] @fabzfta 
- [x] @JanaideNogueira 
- [x] @diogenes-fontenele 
- [x] @mabiapines

**Comment by diogenes-fontenele** [comment]
O Ambiente está ok!

**Comment by bcnishi** [comment]
Ambiente configurado!

**Comment by gabryelsguedes** [comment]
Ambiente está ok!

**Comment by mabiapines** [comment]
tudo ok, graças a Deux

**Comment by mabiapines** [comment]
@JanaideNogueira dá um ok aqui, por favor!

**Comment by JanaideNogueira** [comment]
Ambiente ok!
