### ISSUE TITLE
Entendimento de dados

### ISSUE THREAD

**Issue by aislansf** [atlantico-academy/storm-tellers#2]
A etapa de entendimento dos dados direciona o foco para identificar, coletar e analisar os conjuntos de dados que podem ajudá-lo a cumprir os objetivos do projeto. Esta fase também possui quatro tarefas:

 - [x] **Coletar os dados iniciais**: adquirir os dados necessários e (se necessário) carregá-los em ferramentas de análise.
 - [x] **Descrever os dados**: examinar os dados e documentar suas propriedades superficiais, como formato de dados, número de registros ou identidades de variáveis.
 - [x] **Explorar os dados**: realizar uma análise mais aprofundada nos dados. Consultar, visualizar e identificar relações entre dados e variáveis.
 - [x] **Verificar a qualidade dos dados**: realizar análises a respeito da qualidade dos dados: o quão limpos são? Também é necessário documentar qualquer tipo de problema de qualidade dos dados.

Essa entrega será feita utilizando um notebook com o nome `01 - Exploratory Data Analysis.ipynb`, dentro do diretório `notebooks/`. Tal notebook conterá a descrição dos dados, bem como a Exploração dos mesmos, através da utilização de gráficos e estatísticas descritivas sobre os dados. Além disso, uma análise de qualidade será necessária.

**Comment by omadson** [comment]
Também irei fechar essa issue, visto que já finalizaram a análise exploratória.
