### ISSUE TITLE
Organizar o Read.me

### ISSUE THREAD

**Issue by mabiapines** [atlantico-academy/storm-tellers#4]
- [x]  Explicar, brevemente, sobre o projeto: objetivos, motivações e qual será nosso produto final;
- [x]  Explicar o conjunto de dados: como foi obtido e descrição simples de cada variável;
- [x]  Deixar explícitos os dados que separamos para treino e teste;
- [x]  Descrever as dependências do projeto; 
- [x]  Listar os desenvolvedores.

**Comment by omadson** [comment]
Acho que essa issue pode ser finalizada, correto?

**Comment by diogenes-fontenele** [comment]
> Acho que essa issue pode ser finalizada, correto?

Sim!
